export const adminFields = [
  { field: "name", width: 200 },
  { field: "email", width: 200 },
  { field: "gender" },
  { field: "phone" },
  { field: "role", width: 300 },
  { field: "isVerified", width: 100 },
  { field: "qaiUserName", width: 150 },
  { field: "documentsType", width: 150 },
  { field: "active", width: 200 },
  { field: "isBlocked", width: 150 },
  { field: "activeJobs", width: 150 },
  { field: "submittedJobs", width: 150 },
  { field: "completedJobs", width: 150 },
  { field: "jobLimit", width: 150 },
  { field: "signImage", width: 150 },
  { field: "isJobBlocked", width: 150 },
  { field: "jobLimitLeft", width: 150 },
  { field: "paymentRate", width: 150 },
  { field: "totalWorkingHours", width: 150 },
  { field: "bloodGroup", width: 150 },
  { field: "billingAccountNo", width: 150 },

  {
    field: "ACTIONS",
    renderCell: "button",
    width: 80,
  },
];
export const recruitManagerFields = [
  { field: "name", width: 200 },
  { field: "email", width: 200 },
  { field: "gender", width: 200 },
  { field: "phone", width: 200 },
  { field: "role", width: 300 },
  { field: "isVerified", width: 100 },
  { field: "qaiUserName", width: 150 },
  { field: "documentsType", width: 150 },
  { field: "active", width: 200 },
  { field: "isBlocked", width: 150 },
  { field: "activeJobs", width: 150 },
  { field: "submittedJobs", width: 150 },
  { field: "completedJobs", width: 150 },
  { field: "jobLimit", width: 150 },
  { field: "signImage", width: 150 },
  { field: "isJobBlocked", width: 150 },
  { field: "jobLimitLeft", width: 150 },
  { field: "paymentRate", width: 150 },
  { field: "totalWorkingHours", width: 150 },
  { field: "bloodGroup", width: 150 },
  { field: "billingAccountNo", width: 150 },

  {
    field: "ACTIONS",
    renderCell: "button",
    width: 80,
  },
];
